from datetime import datetime

from typing import Protocol

from sqlalchemy.orm import Session

from onetake_api.modules.project.domain.model import Project


class ProjectRepository(Protocol):
    def add(self, session: Session, project: Project) -> None: ...
    def get(self, session: Session, project_id: str) -> Project | None: ...
    def update(self, session: Session, project: Project) -> None: ...
    def list_projects(self, session: Session, limit: int) -> list[Project]: ...
    def list_expired(self, session: Session, before: datetime) -> list[Project]: ...
